//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 1/25/2010 10:46:05 PM
namespace WindowsFormsApplication1.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for AdventureWorksEntities in the schema.
    /// </summary>
    public partial class AdventureWorksEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.EntityModel.Emitters.EntityContainerEmitter", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("AdventureWorksModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WindowsFormsApplication1.ServiceReference1.AdventureWorksModel", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.EntityModel.Emitters.EntityContainerEmitter", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WindowsFormsApplication1.ServiceReference1.AdventureWorksModel", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AdventureWorksModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Employees in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Employee> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employee>("Employees");
                }
                return this._Employees;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Employee> _Employees;
        /// <summary>
        /// There are no comments for EmployeeAddresses in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<EmployeeAddress> EmployeeAddresses
        {
            get
            {
                if ((this._EmployeeAddresses == null))
                {
                    this._EmployeeAddresses = base.CreateQuery<EmployeeAddress>("EmployeeAddresses");
                }
                return this._EmployeeAddresses;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<EmployeeAddress> _EmployeeAddresses;
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Address> Addresses
        {
            get
            {
                if ((this._Addresses == null))
                {
                    this._Addresses = base.CreateQuery<Address>("Addresses");
                }
                return this._Addresses;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Address> _Addresses;
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Contact> Contacts
        {
            get
            {
                if ((this._Contacts == null))
                {
                    this._Contacts = base.CreateQuery<Contact>("Contacts");
                }
                return this._Contacts;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Contact> _Contacts;
        /// <summary>
        /// There are no comments for StateProvinces in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<StateProvince> StateProvinces
        {
            get
            {
                if ((this._StateProvinces == null))
                {
                    this._StateProvinces = base.CreateQuery<StateProvince>("StateProvinces");
                }
                return this._StateProvinces;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<StateProvince> _StateProvinces;
        /// <summary>
        /// There are no comments for PurchaseOrderHeaders in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<PurchaseOrderHeader> PurchaseOrderHeaders
        {
            get
            {
                if ((this._PurchaseOrderHeaders == null))
                {
                    this._PurchaseOrderHeaders = base.CreateQuery<PurchaseOrderHeader>("PurchaseOrderHeaders");
                }
                return this._PurchaseOrderHeaders;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<PurchaseOrderHeader> _PurchaseOrderHeaders;
        /// <summary>
        /// There are no comments for SalesPersons in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<SalesPerson> SalesPersons
        {
            get
            {
                if ((this._SalesPersons == null))
                {
                    this._SalesPersons = base.CreateQuery<SalesPerson>("SalesPersons");
                }
                return this._SalesPersons;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<SalesPerson> _SalesPersons;
        /// <summary>
        /// There are no comments for SalesTerritories in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<SalesTerritory> SalesTerritories
        {
            get
            {
                if ((this._SalesTerritories == null))
                {
                    this._SalesTerritories = base.CreateQuery<SalesTerritory>("SalesTerritories");
                }
                return this._SalesTerritories;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<SalesTerritory> _SalesTerritories;
        /// <summary>
        /// There are no comments for Employees in the schema.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
        /// <summary>
        /// There are no comments for EmployeeAddresses in the schema.
        /// </summary>
        public void AddToEmployeeAddresses(EmployeeAddress employeeAddress)
        {
            base.AddObject("EmployeeAddresses", employeeAddress);
        }
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        public void AddToContacts(Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
        /// <summary>
        /// There are no comments for StateProvinces in the schema.
        /// </summary>
        public void AddToStateProvinces(StateProvince stateProvince)
        {
            base.AddObject("StateProvinces", stateProvince);
        }
        /// <summary>
        /// There are no comments for PurchaseOrderHeaders in the schema.
        /// </summary>
        public void AddToPurchaseOrderHeaders(PurchaseOrderHeader purchaseOrderHeader)
        {
            base.AddObject("PurchaseOrderHeaders", purchaseOrderHeader);
        }
        /// <summary>
        /// There are no comments for SalesPersons in the schema.
        /// </summary>
        public void AddToSalesPersons(SalesPerson salesPerson)
        {
            base.AddObject("SalesPersons", salesPerson);
        }
        /// <summary>
        /// There are no comments for SalesTerritories in the schema.
        /// </summary>
        public void AddToSalesTerritories(SalesTerritory salesTerritory)
        {
            base.AddObject("SalesTerritories", salesTerritory);
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Employees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")]
    public partial class Employee : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="nationalIDNumber">Initial value of NationalIDNumber.</param>
        /// <param name="contactID">Initial value of ContactID.</param>
        /// <param name="loginID">Initial value of LoginID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="birthDate">Initial value of BirthDate.</param>
        /// <param name="maritalStatus">Initial value of MaritalStatus.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="hireDate">Initial value of HireDate.</param>
        /// <param name="salariedFlag">Initial value of SalariedFlag.</param>
        /// <param name="vacationHours">Initial value of VacationHours.</param>
        /// <param name="sickLeaveHours">Initial value of SickLeaveHours.</param>
        /// <param name="currentFlag">Initial value of CurrentFlag.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Employee CreateEmployee(int employeeID, string nationalIDNumber, int contactID, string loginID, string title, global::System.DateTime birthDate, string maritalStatus, string gender, global::System.DateTime hireDate, bool salariedFlag, short vacationHours, short sickLeaveHours, bool currentFlag, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.NationalIDNumber = nationalIDNumber;
            employee.ContactID = contactID;
            employee.LoginID = loginID;
            employee.Title = title;
            employee.BirthDate = birthDate;
            employee.MaritalStatus = maritalStatus;
            employee.Gender = gender;
            employee.HireDate = hireDate;
            employee.SalariedFlag = salariedFlag;
            employee.VacationHours = vacationHours;
            employee.SickLeaveHours = sickLeaveHours;
            employee.CurrentFlag = currentFlag;
            employee.rowguid = rowguid;
            employee.ModifiedDate = modifiedDate;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property NationalIDNumber in the schema.
        /// </summary>
        public string NationalIDNumber
        {
            get
            {
                return this._NationalIDNumber;
            }
            set
            {
                this.OnNationalIDNumberChanging(value);
                this._NationalIDNumber = value;
                this.OnNationalIDNumberChanged();
                this.OnPropertyChanged("NationalIDNumber");
            }
        }
        private string _NationalIDNumber;
        partial void OnNationalIDNumberChanging(string value);
        partial void OnNationalIDNumberChanged();
        /// <summary>
        /// There are no comments for Property ContactID in the schema.
        /// </summary>
        public int ContactID
        {
            get
            {
                return this._ContactID;
            }
            set
            {
                this.OnContactIDChanging(value);
                this._ContactID = value;
                this.OnContactIDChanged();
                this.OnPropertyChanged("ContactID");
            }
        }
        private int _ContactID;
        partial void OnContactIDChanging(int value);
        partial void OnContactIDChanged();
        /// <summary>
        /// There are no comments for Property LoginID in the schema.
        /// </summary>
        public string LoginID
        {
            get
            {
                return this._LoginID;
            }
            set
            {
                this.OnLoginIDChanging(value);
                this._LoginID = value;
                this.OnLoginIDChanged();
                this.OnPropertyChanged("LoginID");
            }
        }
        private string _LoginID;
        partial void OnLoginIDChanging(string value);
        partial void OnLoginIDChanged();
        /// <summary>
        /// There are no comments for Property ManagerID in the schema.
        /// </summary>
        public global::System.Nullable<int> ManagerID
        {
            get
            {
                return this._ManagerID;
            }
            set
            {
                this.OnManagerIDChanging(value);
                this._ManagerID = value;
                this.OnManagerIDChanged();
                this.OnPropertyChanged("ManagerID");
            }
        }
        private global::System.Nullable<int> _ManagerID;
        partial void OnManagerIDChanging(global::System.Nullable<int> value);
        partial void OnManagerIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property BirthDate in the schema.
        /// </summary>
        public global::System.DateTime BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this._BirthDate = value;
                this.OnBirthDateChanged();
                this.OnPropertyChanged("BirthDate");
            }
        }
        private global::System.DateTime _BirthDate;
        partial void OnBirthDateChanging(global::System.DateTime value);
        partial void OnBirthDateChanged();
        /// <summary>
        /// There are no comments for Property MaritalStatus in the schema.
        /// </summary>
        public string MaritalStatus
        {
            get
            {
                return this._MaritalStatus;
            }
            set
            {
                this.OnMaritalStatusChanging(value);
                this._MaritalStatus = value;
                this.OnMaritalStatusChanged();
                this.OnPropertyChanged("MaritalStatus");
            }
        }
        private string _MaritalStatus;
        partial void OnMaritalStatusChanging(string value);
        partial void OnMaritalStatusChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        private string _Gender;
        partial void OnGenderChanging(string value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property HireDate in the schema.
        /// </summary>
        public global::System.DateTime HireDate
        {
            get
            {
                return this._HireDate;
            }
            set
            {
                this.OnHireDateChanging(value);
                this._HireDate = value;
                this.OnHireDateChanged();
                this.OnPropertyChanged("HireDate");
            }
        }
        private global::System.DateTime _HireDate;
        partial void OnHireDateChanging(global::System.DateTime value);
        partial void OnHireDateChanged();
        /// <summary>
        /// There are no comments for Property SalariedFlag in the schema.
        /// </summary>
        public bool SalariedFlag
        {
            get
            {
                return this._SalariedFlag;
            }
            set
            {
                this.OnSalariedFlagChanging(value);
                this._SalariedFlag = value;
                this.OnSalariedFlagChanged();
                this.OnPropertyChanged("SalariedFlag");
            }
        }
        private bool _SalariedFlag;
        partial void OnSalariedFlagChanging(bool value);
        partial void OnSalariedFlagChanged();
        /// <summary>
        /// There are no comments for Property VacationHours in the schema.
        /// </summary>
        public short VacationHours
        {
            get
            {
                return this._VacationHours;
            }
            set
            {
                this.OnVacationHoursChanging(value);
                this._VacationHours = value;
                this.OnVacationHoursChanged();
                this.OnPropertyChanged("VacationHours");
            }
        }
        private short _VacationHours;
        partial void OnVacationHoursChanging(short value);
        partial void OnVacationHoursChanged();
        /// <summary>
        /// There are no comments for Property SickLeaveHours in the schema.
        /// </summary>
        public short SickLeaveHours
        {
            get
            {
                return this._SickLeaveHours;
            }
            set
            {
                this.OnSickLeaveHoursChanging(value);
                this._SickLeaveHours = value;
                this.OnSickLeaveHoursChanged();
                this.OnPropertyChanged("SickLeaveHours");
            }
        }
        private short _SickLeaveHours;
        partial void OnSickLeaveHoursChanging(short value);
        partial void OnSickLeaveHoursChanged();
        /// <summary>
        /// There are no comments for Property CurrentFlag in the schema.
        /// </summary>
        public bool CurrentFlag
        {
            get
            {
                return this._CurrentFlag;
            }
            set
            {
                this.OnCurrentFlagChanging(value);
                this._CurrentFlag = value;
                this.OnCurrentFlagChanged();
                this.OnPropertyChanged("CurrentFlag");
            }
        }
        private bool _CurrentFlag;
        partial void OnCurrentFlagChanging(bool value);
        partial void OnCurrentFlagChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public Contact Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this._Contact = value;
                this.OnPropertyChanged("Contact");
            }
        }
        private Contact _Contact;
        /// <summary>
        /// There are no comments for Employee1 in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<Employee> Employee1
        {
            get
            {
                return this._Employee1;
            }
            set
            {
                this._Employee1 = value;
                this.OnPropertyChanged("Employee1");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<Employee> _Employee1 = System.Data.Services.Client.DataServiceCollection.Create<Employee>();
        /// <summary>
        /// There are no comments for Employee2 in the schema.
        /// </summary>
        public Employee Employee2
        {
            get
            {
                return this._Employee2;
            }
            set
            {
                this._Employee2 = value;
                this.OnPropertyChanged("Employee2");
            }
        }
        private Employee _Employee2;
        /// <summary>
        /// There are no comments for EmployeeAddresses in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<EmployeeAddress> EmployeeAddresses
        {
            get
            {
                return this._EmployeeAddresses;
            }
            set
            {
                this._EmployeeAddresses = value;
                this.OnPropertyChanged("EmployeeAddresses");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<EmployeeAddress> _EmployeeAddresses = System.Data.Services.Client.DataServiceCollection.Create<EmployeeAddress>();
        /// <summary>
        /// There are no comments for PurchaseOrderHeaders in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<PurchaseOrderHeader> PurchaseOrderHeaders
        {
            get
            {
                return this._PurchaseOrderHeaders;
            }
            set
            {
                this._PurchaseOrderHeaders = value;
                this.OnPropertyChanged("PurchaseOrderHeaders");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<PurchaseOrderHeader> _PurchaseOrderHeaders = System.Data.Services.Client.DataServiceCollection.Create<PurchaseOrderHeader>();
        /// <summary>
        /// There are no comments for SalesPerson in the schema.
        /// </summary>
        public SalesPerson SalesPerson
        {
            get
            {
                return this._SalesPerson;
            }
            set
            {
                this._SalesPerson = value;
                this.OnPropertyChanged("SalesPerson");
            }
        }
        private SalesPerson _SalesPerson;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.EmployeeAddress in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// AddressID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EmployeeAddresses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID", "AddressID")]
    public partial class EmployeeAddress : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EmployeeAddress object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="addressID">Initial value of AddressID.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static EmployeeAddress CreateEmployeeAddress(int employeeID, int addressID, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            EmployeeAddress employeeAddress = new EmployeeAddress();
            employeeAddress.EmployeeID = employeeID;
            employeeAddress.AddressID = addressID;
            employeeAddress.rowguid = rowguid;
            employeeAddress.ModifiedDate = modifiedDate;
            return employeeAddress;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property AddressID in the schema.
        /// </summary>
        public int AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this.OnAddressIDChanging(value);
                this._AddressID = value;
                this.OnAddressIDChanged();
                this.OnPropertyChanged("AddressID");
            }
        }
        private int _AddressID;
        partial void OnAddressIDChanging(int value);
        partial void OnAddressIDChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public Employee Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this._Employee = value;
                this.OnPropertyChanged("Employee");
            }
        }
        private Employee _Employee;
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
                this.OnPropertyChanged("Address");
            }
        }
        private Address _Address;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.Address in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AddressID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Addresses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AddressID")]
    public partial class Address : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="addressID">Initial value of AddressID.</param>
        /// <param name="addressLine1">Initial value of AddressLine1.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="stateProvinceID">Initial value of StateProvinceID.</param>
        /// <param name="postalCode">Initial value of PostalCode.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Address CreateAddress(int addressID, string addressLine1, string city, int stateProvinceID, string postalCode, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Address address = new Address();
            address.AddressID = addressID;
            address.AddressLine1 = addressLine1;
            address.City = city;
            address.StateProvinceID = stateProvinceID;
            address.PostalCode = postalCode;
            address.rowguid = rowguid;
            address.ModifiedDate = modifiedDate;
            return address;
        }
        /// <summary>
        /// There are no comments for Property AddressID in the schema.
        /// </summary>
        public int AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this.OnAddressIDChanging(value);
                this._AddressID = value;
                this.OnAddressIDChanged();
                this.OnPropertyChanged("AddressID");
            }
        }
        private int _AddressID;
        partial void OnAddressIDChanging(int value);
        partial void OnAddressIDChanged();
        /// <summary>
        /// There are no comments for Property AddressLine1 in the schema.
        /// </summary>
        public string AddressLine1
        {
            get
            {
                return this._AddressLine1;
            }
            set
            {
                this.OnAddressLine1Changing(value);
                this._AddressLine1 = value;
                this.OnAddressLine1Changed();
                this.OnPropertyChanged("AddressLine1");
            }
        }
        private string _AddressLine1;
        partial void OnAddressLine1Changing(string value);
        partial void OnAddressLine1Changed();
        /// <summary>
        /// There are no comments for Property AddressLine2 in the schema.
        /// </summary>
        public string AddressLine2
        {
            get
            {
                return this._AddressLine2;
            }
            set
            {
                this.OnAddressLine2Changing(value);
                this._AddressLine2 = value;
                this.OnAddressLine2Changed();
                this.OnPropertyChanged("AddressLine2");
            }
        }
        private string _AddressLine2;
        partial void OnAddressLine2Changing(string value);
        partial void OnAddressLine2Changed();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property StateProvinceID in the schema.
        /// </summary>
        public int StateProvinceID
        {
            get
            {
                return this._StateProvinceID;
            }
            set
            {
                this.OnStateProvinceIDChanging(value);
                this._StateProvinceID = value;
                this.OnStateProvinceIDChanged();
                this.OnPropertyChanged("StateProvinceID");
            }
        }
        private int _StateProvinceID;
        partial void OnStateProvinceIDChanging(int value);
        partial void OnStateProvinceIDChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
                this.OnPropertyChanged("PostalCode");
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for EmployeeAddresses in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<EmployeeAddress> EmployeeAddresses
        {
            get
            {
                return this._EmployeeAddresses;
            }
            set
            {
                this._EmployeeAddresses = value;
                this.OnPropertyChanged("EmployeeAddresses");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<EmployeeAddress> _EmployeeAddresses = System.Data.Services.Client.DataServiceCollection.Create<EmployeeAddress>();
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        public StateProvince StateProvince
        {
            get
            {
                return this._StateProvince;
            }
            set
            {
                this._StateProvince = value;
                this.OnPropertyChanged("StateProvince");
            }
        }
        private StateProvince _StateProvince;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ContactID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Contacts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ContactID")]
    public partial class Contact : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="contactID">Initial value of ContactID.</param>
        /// <param name="nameStyle">Initial value of NameStyle.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="emailPromotion">Initial value of EmailPromotion.</param>
        /// <param name="passwordHash">Initial value of PasswordHash.</param>
        /// <param name="passwordSalt">Initial value of PasswordSalt.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Contact CreateContact(int contactID, bool nameStyle, string firstName, string lastName, int emailPromotion, string passwordHash, string passwordSalt, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Contact contact = new Contact();
            contact.ContactID = contactID;
            contact.NameStyle = nameStyle;
            contact.FirstName = firstName;
            contact.LastName = lastName;
            contact.EmailPromotion = emailPromotion;
            contact.PasswordHash = passwordHash;
            contact.PasswordSalt = passwordSalt;
            contact.rowguid = rowguid;
            contact.ModifiedDate = modifiedDate;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property ContactID in the schema.
        /// </summary>
        public int ContactID
        {
            get
            {
                return this._ContactID;
            }
            set
            {
                this.OnContactIDChanging(value);
                this._ContactID = value;
                this.OnContactIDChanged();
                this.OnPropertyChanged("ContactID");
            }
        }
        private int _ContactID;
        partial void OnContactIDChanging(int value);
        partial void OnContactIDChanged();
        /// <summary>
        /// There are no comments for Property NameStyle in the schema.
        /// </summary>
        public bool NameStyle
        {
            get
            {
                return this._NameStyle;
            }
            set
            {
                this.OnNameStyleChanging(value);
                this._NameStyle = value;
                this.OnNameStyleChanged();
                this.OnPropertyChanged("NameStyle");
            }
        }
        private bool _NameStyle;
        partial void OnNameStyleChanging(bool value);
        partial void OnNameStyleChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Suffix in the schema.
        /// </summary>
        public string Suffix
        {
            get
            {
                return this._Suffix;
            }
            set
            {
                this.OnSuffixChanging(value);
                this._Suffix = value;
                this.OnSuffixChanged();
                this.OnPropertyChanged("Suffix");
            }
        }
        private string _Suffix;
        partial void OnSuffixChanging(string value);
        partial void OnSuffixChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property EmailPromotion in the schema.
        /// </summary>
        public int EmailPromotion
        {
            get
            {
                return this._EmailPromotion;
            }
            set
            {
                this.OnEmailPromotionChanging(value);
                this._EmailPromotion = value;
                this.OnEmailPromotionChanged();
                this.OnPropertyChanged("EmailPromotion");
            }
        }
        private int _EmailPromotion;
        partial void OnEmailPromotionChanging(int value);
        partial void OnEmailPromotionChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property PasswordHash in the schema.
        /// </summary>
        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
                this.OnPropertyChanged("PasswordHash");
            }
        }
        private string _PasswordHash;
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        public string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
                this.OnPropertyChanged("PasswordSalt");
            }
        }
        private string _PasswordSalt;
        partial void OnPasswordSaltChanging(string value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property AdditionalContactInfo in the schema.
        /// </summary>
        public string AdditionalContactInfo
        {
            get
            {
                return this._AdditionalContactInfo;
            }
            set
            {
                this.OnAdditionalContactInfoChanging(value);
                this._AdditionalContactInfo = value;
                this.OnAdditionalContactInfoChanged();
                this.OnPropertyChanged("AdditionalContactInfo");
            }
        }
        private string _AdditionalContactInfo;
        partial void OnAdditionalContactInfoChanging(string value);
        partial void OnAdditionalContactInfoChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Employees in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<Employee> Employees
        {
            get
            {
                return this._Employees;
            }
            set
            {
                this._Employees = value;
                this.OnPropertyChanged("Employees");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<Employee> _Employees = System.Data.Services.Client.DataServiceCollection.Create<Employee>();
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.StateProvince in the schema.
    /// </summary>
    /// <KeyProperties>
    /// StateProvinceID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("StateProvinces")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("StateProvinceID")]
    public partial class StateProvince : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new StateProvince object.
        /// </summary>
        /// <param name="stateProvinceID">Initial value of StateProvinceID.</param>
        /// <param name="stateProvinceCode">Initial value of StateProvinceCode.</param>
        /// <param name="countryRegionCode">Initial value of CountryRegionCode.</param>
        /// <param name="isOnlyStateProvinceFlag">Initial value of IsOnlyStateProvinceFlag.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="territoryID">Initial value of TerritoryID.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static StateProvince CreateStateProvince(int stateProvinceID, string stateProvinceCode, string countryRegionCode, bool isOnlyStateProvinceFlag, string name, int territoryID, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            StateProvince stateProvince = new StateProvince();
            stateProvince.StateProvinceID = stateProvinceID;
            stateProvince.StateProvinceCode = stateProvinceCode;
            stateProvince.CountryRegionCode = countryRegionCode;
            stateProvince.IsOnlyStateProvinceFlag = isOnlyStateProvinceFlag;
            stateProvince.Name = name;
            stateProvince.TerritoryID = territoryID;
            stateProvince.rowguid = rowguid;
            stateProvince.ModifiedDate = modifiedDate;
            return stateProvince;
        }
        /// <summary>
        /// There are no comments for Property StateProvinceID in the schema.
        /// </summary>
        public int StateProvinceID
        {
            get
            {
                return this._StateProvinceID;
            }
            set
            {
                this.OnStateProvinceIDChanging(value);
                this._StateProvinceID = value;
                this.OnStateProvinceIDChanged();
                this.OnPropertyChanged("StateProvinceID");
            }
        }
        private int _StateProvinceID;
        partial void OnStateProvinceIDChanging(int value);
        partial void OnStateProvinceIDChanged();
        /// <summary>
        /// There are no comments for Property StateProvinceCode in the schema.
        /// </summary>
        public string StateProvinceCode
        {
            get
            {
                return this._StateProvinceCode;
            }
            set
            {
                this.OnStateProvinceCodeChanging(value);
                this._StateProvinceCode = value;
                this.OnStateProvinceCodeChanged();
                this.OnPropertyChanged("StateProvinceCode");
            }
        }
        private string _StateProvinceCode;
        partial void OnStateProvinceCodeChanging(string value);
        partial void OnStateProvinceCodeChanged();
        /// <summary>
        /// There are no comments for Property CountryRegionCode in the schema.
        /// </summary>
        public string CountryRegionCode
        {
            get
            {
                return this._CountryRegionCode;
            }
            set
            {
                this.OnCountryRegionCodeChanging(value);
                this._CountryRegionCode = value;
                this.OnCountryRegionCodeChanged();
                this.OnPropertyChanged("CountryRegionCode");
            }
        }
        private string _CountryRegionCode;
        partial void OnCountryRegionCodeChanging(string value);
        partial void OnCountryRegionCodeChanged();
        /// <summary>
        /// There are no comments for Property IsOnlyStateProvinceFlag in the schema.
        /// </summary>
        public bool IsOnlyStateProvinceFlag
        {
            get
            {
                return this._IsOnlyStateProvinceFlag;
            }
            set
            {
                this.OnIsOnlyStateProvinceFlagChanging(value);
                this._IsOnlyStateProvinceFlag = value;
                this.OnIsOnlyStateProvinceFlagChanged();
                this.OnPropertyChanged("IsOnlyStateProvinceFlag");
            }
        }
        private bool _IsOnlyStateProvinceFlag;
        partial void OnIsOnlyStateProvinceFlagChanging(bool value);
        partial void OnIsOnlyStateProvinceFlagChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property TerritoryID in the schema.
        /// </summary>
        public int TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this.OnTerritoryIDChanging(value);
                this._TerritoryID = value;
                this.OnTerritoryIDChanged();
                this.OnPropertyChanged("TerritoryID");
            }
        }
        private int _TerritoryID;
        partial void OnTerritoryIDChanging(int value);
        partial void OnTerritoryIDChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<Address> Addresses
        {
            get
            {
                return this._Addresses;
            }
            set
            {
                this._Addresses = value;
                this.OnPropertyChanged("Addresses");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<Address> _Addresses = System.Data.Services.Client.DataServiceCollection.Create<Address>();
        /// <summary>
        /// There are no comments for SalesTerritory in the schema.
        /// </summary>
        public SalesTerritory SalesTerritory
        {
            get
            {
                return this._SalesTerritory;
            }
            set
            {
                this._SalesTerritory = value;
                this.OnPropertyChanged("SalesTerritory");
            }
        }
        private SalesTerritory _SalesTerritory;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.PurchaseOrderHeader in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PurchaseOrderID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PurchaseOrderHeaders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PurchaseOrderID")]
    public partial class PurchaseOrderHeader : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PurchaseOrderHeader object.
        /// </summary>
        /// <param name="purchaseOrderID">Initial value of PurchaseOrderID.</param>
        /// <param name="revisionNumber">Initial value of RevisionNumber.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="vendorID">Initial value of VendorID.</param>
        /// <param name="shipMethodID">Initial value of ShipMethodID.</param>
        /// <param name="orderDate">Initial value of OrderDate.</param>
        /// <param name="subTotal">Initial value of SubTotal.</param>
        /// <param name="taxAmt">Initial value of TaxAmt.</param>
        /// <param name="freight">Initial value of Freight.</param>
        /// <param name="totalDue">Initial value of TotalDue.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static PurchaseOrderHeader CreatePurchaseOrderHeader(int purchaseOrderID, byte revisionNumber, byte status, int employeeID, int vendorID, int shipMethodID, global::System.DateTime orderDate, decimal subTotal, decimal taxAmt, decimal freight, decimal totalDue, global::System.DateTime modifiedDate)
        {
            PurchaseOrderHeader purchaseOrderHeader = new PurchaseOrderHeader();
            purchaseOrderHeader.PurchaseOrderID = purchaseOrderID;
            purchaseOrderHeader.RevisionNumber = revisionNumber;
            purchaseOrderHeader.Status = status;
            purchaseOrderHeader.EmployeeID = employeeID;
            purchaseOrderHeader.VendorID = vendorID;
            purchaseOrderHeader.ShipMethodID = shipMethodID;
            purchaseOrderHeader.OrderDate = orderDate;
            purchaseOrderHeader.SubTotal = subTotal;
            purchaseOrderHeader.TaxAmt = taxAmt;
            purchaseOrderHeader.Freight = freight;
            purchaseOrderHeader.TotalDue = totalDue;
            purchaseOrderHeader.ModifiedDate = modifiedDate;
            return purchaseOrderHeader;
        }
        /// <summary>
        /// There are no comments for Property PurchaseOrderID in the schema.
        /// </summary>
        public int PurchaseOrderID
        {
            get
            {
                return this._PurchaseOrderID;
            }
            set
            {
                this.OnPurchaseOrderIDChanging(value);
                this._PurchaseOrderID = value;
                this.OnPurchaseOrderIDChanged();
                this.OnPropertyChanged("PurchaseOrderID");
            }
        }
        private int _PurchaseOrderID;
        partial void OnPurchaseOrderIDChanging(int value);
        partial void OnPurchaseOrderIDChanged();
        /// <summary>
        /// There are no comments for Property RevisionNumber in the schema.
        /// </summary>
        public byte RevisionNumber
        {
            get
            {
                return this._RevisionNumber;
            }
            set
            {
                this.OnRevisionNumberChanging(value);
                this._RevisionNumber = value;
                this.OnRevisionNumberChanged();
                this.OnPropertyChanged("RevisionNumber");
            }
        }
        private byte _RevisionNumber;
        partial void OnRevisionNumberChanging(byte value);
        partial void OnRevisionNumberChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        public byte Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        private byte _Status;
        partial void OnStatusChanging(byte value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property VendorID in the schema.
        /// </summary>
        public int VendorID
        {
            get
            {
                return this._VendorID;
            }
            set
            {
                this.OnVendorIDChanging(value);
                this._VendorID = value;
                this.OnVendorIDChanged();
                this.OnPropertyChanged("VendorID");
            }
        }
        private int _VendorID;
        partial void OnVendorIDChanging(int value);
        partial void OnVendorIDChanged();
        /// <summary>
        /// There are no comments for Property ShipMethodID in the schema.
        /// </summary>
        public int ShipMethodID
        {
            get
            {
                return this._ShipMethodID;
            }
            set
            {
                this.OnShipMethodIDChanging(value);
                this._ShipMethodID = value;
                this.OnShipMethodIDChanged();
                this.OnPropertyChanged("ShipMethodID");
            }
        }
        private int _ShipMethodID;
        partial void OnShipMethodIDChanging(int value);
        partial void OnShipMethodIDChanged();
        /// <summary>
        /// There are no comments for Property OrderDate in the schema.
        /// </summary>
        public global::System.DateTime OrderDate
        {
            get
            {
                return this._OrderDate;
            }
            set
            {
                this.OnOrderDateChanging(value);
                this._OrderDate = value;
                this.OnOrderDateChanged();
                this.OnPropertyChanged("OrderDate");
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
        /// <summary>
        /// There are no comments for Property ShipDate in the schema.
        /// </summary>
        public global::System.Nullable<global::System.DateTime> ShipDate
        {
            get
            {
                return this._ShipDate;
            }
            set
            {
                this.OnShipDateChanging(value);
                this._ShipDate = value;
                this.OnShipDateChanged();
                this.OnPropertyChanged("ShipDate");
            }
        }
        private global::System.Nullable<global::System.DateTime> _ShipDate;
        partial void OnShipDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnShipDateChanged();
        /// <summary>
        /// There are no comments for Property SubTotal in the schema.
        /// </summary>
        public decimal SubTotal
        {
            get
            {
                return this._SubTotal;
            }
            set
            {
                this.OnSubTotalChanging(value);
                this._SubTotal = value;
                this.OnSubTotalChanged();
                this.OnPropertyChanged("SubTotal");
            }
        }
        private decimal _SubTotal;
        partial void OnSubTotalChanging(decimal value);
        partial void OnSubTotalChanged();
        /// <summary>
        /// There are no comments for Property TaxAmt in the schema.
        /// </summary>
        public decimal TaxAmt
        {
            get
            {
                return this._TaxAmt;
            }
            set
            {
                this.OnTaxAmtChanging(value);
                this._TaxAmt = value;
                this.OnTaxAmtChanged();
                this.OnPropertyChanged("TaxAmt");
            }
        }
        private decimal _TaxAmt;
        partial void OnTaxAmtChanging(decimal value);
        partial void OnTaxAmtChanged();
        /// <summary>
        /// There are no comments for Property Freight in the schema.
        /// </summary>
        public decimal Freight
        {
            get
            {
                return this._Freight;
            }
            set
            {
                this.OnFreightChanging(value);
                this._Freight = value;
                this.OnFreightChanged();
                this.OnPropertyChanged("Freight");
            }
        }
        private decimal _Freight;
        partial void OnFreightChanging(decimal value);
        partial void OnFreightChanged();
        /// <summary>
        /// There are no comments for Property TotalDue in the schema.
        /// </summary>
        public decimal TotalDue
        {
            get
            {
                return this._TotalDue;
            }
            set
            {
                this.OnTotalDueChanging(value);
                this._TotalDue = value;
                this.OnTotalDueChanged();
                this.OnPropertyChanged("TotalDue");
            }
        }
        private decimal _TotalDue;
        partial void OnTotalDueChanging(decimal value);
        partial void OnTotalDueChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public Employee Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this._Employee = value;
                this.OnPropertyChanged("Employee");
            }
        }
        private Employee _Employee;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.SalesPerson in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SalesPersonID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SalesPersons")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SalesPersonID")]
    public partial class SalesPerson : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SalesPerson object.
        /// </summary>
        /// <param name="salesPersonID">Initial value of SalesPersonID.</param>
        /// <param name="bonus">Initial value of Bonus.</param>
        /// <param name="commissionPct">Initial value of CommissionPct.</param>
        /// <param name="salesYTD">Initial value of SalesYTD.</param>
        /// <param name="salesLastYear">Initial value of SalesLastYear.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static SalesPerson CreateSalesPerson(int salesPersonID, decimal bonus, decimal commissionPct, decimal salesYTD, decimal salesLastYear, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            SalesPerson salesPerson = new SalesPerson();
            salesPerson.SalesPersonID = salesPersonID;
            salesPerson.Bonus = bonus;
            salesPerson.CommissionPct = commissionPct;
            salesPerson.SalesYTD = salesYTD;
            salesPerson.SalesLastYear = salesLastYear;
            salesPerson.rowguid = rowguid;
            salesPerson.ModifiedDate = modifiedDate;
            return salesPerson;
        }
        /// <summary>
        /// There are no comments for Property SalesPersonID in the schema.
        /// </summary>
        public int SalesPersonID
        {
            get
            {
                return this._SalesPersonID;
            }
            set
            {
                this.OnSalesPersonIDChanging(value);
                this._SalesPersonID = value;
                this.OnSalesPersonIDChanged();
                this.OnPropertyChanged("SalesPersonID");
            }
        }
        private int _SalesPersonID;
        partial void OnSalesPersonIDChanging(int value);
        partial void OnSalesPersonIDChanged();
        /// <summary>
        /// There are no comments for Property TerritoryID in the schema.
        /// </summary>
        public global::System.Nullable<int> TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this.OnTerritoryIDChanging(value);
                this._TerritoryID = value;
                this.OnTerritoryIDChanged();
                this.OnPropertyChanged("TerritoryID");
            }
        }
        private global::System.Nullable<int> _TerritoryID;
        partial void OnTerritoryIDChanging(global::System.Nullable<int> value);
        partial void OnTerritoryIDChanged();
        /// <summary>
        /// There are no comments for Property SalesQuota in the schema.
        /// </summary>
        public global::System.Nullable<decimal> SalesQuota
        {
            get
            {
                return this._SalesQuota;
            }
            set
            {
                this.OnSalesQuotaChanging(value);
                this._SalesQuota = value;
                this.OnSalesQuotaChanged();
                this.OnPropertyChanged("SalesQuota");
            }
        }
        private global::System.Nullable<decimal> _SalesQuota;
        partial void OnSalesQuotaChanging(global::System.Nullable<decimal> value);
        partial void OnSalesQuotaChanged();
        /// <summary>
        /// There are no comments for Property Bonus in the schema.
        /// </summary>
        public decimal Bonus
        {
            get
            {
                return this._Bonus;
            }
            set
            {
                this.OnBonusChanging(value);
                this._Bonus = value;
                this.OnBonusChanged();
                this.OnPropertyChanged("Bonus");
            }
        }
        private decimal _Bonus;
        partial void OnBonusChanging(decimal value);
        partial void OnBonusChanged();
        /// <summary>
        /// There are no comments for Property CommissionPct in the schema.
        /// </summary>
        public decimal CommissionPct
        {
            get
            {
                return this._CommissionPct;
            }
            set
            {
                this.OnCommissionPctChanging(value);
                this._CommissionPct = value;
                this.OnCommissionPctChanged();
                this.OnPropertyChanged("CommissionPct");
            }
        }
        private decimal _CommissionPct;
        partial void OnCommissionPctChanging(decimal value);
        partial void OnCommissionPctChanged();
        /// <summary>
        /// There are no comments for Property SalesYTD in the schema.
        /// </summary>
        public decimal SalesYTD
        {
            get
            {
                return this._SalesYTD;
            }
            set
            {
                this.OnSalesYTDChanging(value);
                this._SalesYTD = value;
                this.OnSalesYTDChanged();
                this.OnPropertyChanged("SalesYTD");
            }
        }
        private decimal _SalesYTD;
        partial void OnSalesYTDChanging(decimal value);
        partial void OnSalesYTDChanged();
        /// <summary>
        /// There are no comments for Property SalesLastYear in the schema.
        /// </summary>
        public decimal SalesLastYear
        {
            get
            {
                return this._SalesLastYear;
            }
            set
            {
                this.OnSalesLastYearChanging(value);
                this._SalesLastYear = value;
                this.OnSalesLastYearChanged();
                this.OnPropertyChanged("SalesLastYear");
            }
        }
        private decimal _SalesLastYear;
        partial void OnSalesLastYearChanging(decimal value);
        partial void OnSalesLastYearChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public Employee Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this._Employee = value;
                this.OnPropertyChanged("Employee");
            }
        }
        private Employee _Employee;
        /// <summary>
        /// There are no comments for SalesTerritory in the schema.
        /// </summary>
        public SalesTerritory SalesTerritory
        {
            get
            {
                return this._SalesTerritory;
            }
            set
            {
                this._SalesTerritory = value;
                this.OnPropertyChanged("SalesTerritory");
            }
        }
        private SalesTerritory _SalesTerritory;
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.SalesTerritory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TerritoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SalesTerritories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TerritoryID")]
    public partial class SalesTerritory : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SalesTerritory object.
        /// </summary>
        /// <param name="territoryID">Initial value of TerritoryID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="countryRegionCode">Initial value of CountryRegionCode.</param>
        /// <param name="group">Initial value of Group.</param>
        /// <param name="salesYTD">Initial value of SalesYTD.</param>
        /// <param name="salesLastYear">Initial value of SalesLastYear.</param>
        /// <param name="costYTD">Initial value of CostYTD.</param>
        /// <param name="costLastYear">Initial value of CostLastYear.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static SalesTerritory CreateSalesTerritory(int territoryID, string name, string countryRegionCode, string group, decimal salesYTD, decimal salesLastYear, decimal costYTD, decimal costLastYear, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            SalesTerritory salesTerritory = new SalesTerritory();
            salesTerritory.TerritoryID = territoryID;
            salesTerritory.Name = name;
            salesTerritory.CountryRegionCode = countryRegionCode;
            salesTerritory.Group = group;
            salesTerritory.SalesYTD = salesYTD;
            salesTerritory.SalesLastYear = salesLastYear;
            salesTerritory.CostYTD = costYTD;
            salesTerritory.CostLastYear = costLastYear;
            salesTerritory.rowguid = rowguid;
            salesTerritory.ModifiedDate = modifiedDate;
            return salesTerritory;
        }
        /// <summary>
        /// There are no comments for Property TerritoryID in the schema.
        /// </summary>
        public int TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this.OnTerritoryIDChanging(value);
                this._TerritoryID = value;
                this.OnTerritoryIDChanged();
                this.OnPropertyChanged("TerritoryID");
            }
        }
        private int _TerritoryID;
        partial void OnTerritoryIDChanging(int value);
        partial void OnTerritoryIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CountryRegionCode in the schema.
        /// </summary>
        public string CountryRegionCode
        {
            get
            {
                return this._CountryRegionCode;
            }
            set
            {
                this.OnCountryRegionCodeChanging(value);
                this._CountryRegionCode = value;
                this.OnCountryRegionCodeChanged();
                this.OnPropertyChanged("CountryRegionCode");
            }
        }
        private string _CountryRegionCode;
        partial void OnCountryRegionCodeChanging(string value);
        partial void OnCountryRegionCodeChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        public string Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        private string _Group;
        partial void OnGroupChanging(string value);
        partial void OnGroupChanged();
        /// <summary>
        /// There are no comments for Property SalesYTD in the schema.
        /// </summary>
        public decimal SalesYTD
        {
            get
            {
                return this._SalesYTD;
            }
            set
            {
                this.OnSalesYTDChanging(value);
                this._SalesYTD = value;
                this.OnSalesYTDChanged();
                this.OnPropertyChanged("SalesYTD");
            }
        }
        private decimal _SalesYTD;
        partial void OnSalesYTDChanging(decimal value);
        partial void OnSalesYTDChanged();
        /// <summary>
        /// There are no comments for Property SalesLastYear in the schema.
        /// </summary>
        public decimal SalesLastYear
        {
            get
            {
                return this._SalesLastYear;
            }
            set
            {
                this.OnSalesLastYearChanging(value);
                this._SalesLastYear = value;
                this.OnSalesLastYearChanged();
                this.OnPropertyChanged("SalesLastYear");
            }
        }
        private decimal _SalesLastYear;
        partial void OnSalesLastYearChanging(decimal value);
        partial void OnSalesLastYearChanged();
        /// <summary>
        /// There are no comments for Property CostYTD in the schema.
        /// </summary>
        public decimal CostYTD
        {
            get
            {
                return this._CostYTD;
            }
            set
            {
                this.OnCostYTDChanging(value);
                this._CostYTD = value;
                this.OnCostYTDChanged();
                this.OnPropertyChanged("CostYTD");
            }
        }
        private decimal _CostYTD;
        partial void OnCostYTDChanging(decimal value);
        partial void OnCostYTDChanged();
        /// <summary>
        /// There are no comments for Property CostLastYear in the schema.
        /// </summary>
        public decimal CostLastYear
        {
            get
            {
                return this._CostLastYear;
            }
            set
            {
                this.OnCostLastYearChanging(value);
                this._CostLastYear = value;
                this.OnCostLastYearChanged();
                this.OnPropertyChanged("CostLastYear");
            }
        }
        private decimal _CostLastYear;
        partial void OnCostLastYearChanging(decimal value);
        partial void OnCostLastYearChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for StateProvinces in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<StateProvince> StateProvinces
        {
            get
            {
                return this._StateProvinces;
            }
            set
            {
                this._StateProvinces = value;
                this.OnPropertyChanged("StateProvinces");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<StateProvince> _StateProvinces = System.Data.Services.Client.DataServiceCollection.Create<StateProvince>();
        /// <summary>
        /// There are no comments for SalesPersons in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceCollection<SalesPerson> SalesPersons
        {
            get
            {
                return this._SalesPersons;
            }
            set
            {
                this._SalesPersons = value;
                this.OnPropertyChanged("SalesPersons");
            }
        }
        private global::System.Data.Services.Client.DataServiceCollection<SalesPerson> _SalesPersons = System.Data.Services.Client.DataServiceCollection.Create<SalesPerson>();
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
